[dev]
  command = "npm run dev"

[build]
  command = "npm run deploy"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "https://www.lilcafe.co"
  to = "https://www.plumbtennant.com.au"

[[redirects]]
  from = "/old-path"
  to = "/new-path"