[dev]
  command = "npm run dev"

[build]
  command = "npm run deploy"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "http://www.lilcafe.co"
  to = "https://www.plumbtennant.com.au"
  
[[redirects]]
  from = "http://lilcafe.co"
  to = "https://www.plumbtennant.com.au"